url: https://snu-vision-test.github.io
# baseurl: /agency-jekyll-theme/
google-tracking-id: "UA-64119252-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

# force-https: True

collections:
  - people
  - courses
  - publications

# HTML Head
title: "Vision & Learning Lab"
lang: en
description: "Vision and Learning, Seoul National University"
keywords: "SNU, Seoul National University, Vision Lab, Computer Vision, Vision, Machine Learning, Learning, Deep Learning, Big Data, Gunhee Kim"
favicon: /img/favicon.ico

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Intro Layout
logo-white-img: /img/logo/snu-logo

# Sections shown in the index page

pages_list:
  About: 'about'
  People: 'people'
  Publications: 'portfolio'
  Courses: 'courses'

# number of recent papers scrolled in flexslider
num_publications_slide: 3

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

social:
  - title: github
    url: https://github.com/snuvl

# Postal address (add as many lines as necessary)
address:
  - line: Room 420-2, 302 Building
  - line: 1 Gwanak-ro, Gwanak-gu Seoul 151-744 Republic of Korea
  - line: "TEL: +82-02-880-7289"

# Build settings
markdown: kramdown
permalink: pretty
